name: CI

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop
jobs:
  test:
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
        platform: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: |
          python -m pip install tox tox-gh-actions
      - name: Run tests
        run: tox
